# -*- coding: utf-8 -*-
"""ensemble+.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-Gmc8WNuHaqldt_ea7GhNL_3Ea2KRQr
"""

import cv2
import glob
import os
import numpy as np

paths_groundtruth  = sorted(glob.glob('./input_ground_truth/*.tif'))
for p_gt in paths_groundtruth:
    img = cv2.imread(p_gt, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print(f"読み込み失敗: {p_gt}")
        continue
    else :
      new_size = (img.shape[1] // 4, img.shape[0] // 4)
      img_resized = cv2.resize(img, new_size, interpolation=cv2.INTER_CUBIC)
      filename = os.path.basename(p_gt)
      save_path = os.path.join('./inputs', f"input_{filename}")
      cv2.imwrite(save_path, img_resized)
      print("bicubic終わり")

import subprocess


cmd = [
    "python",
    "./Real-ESRGAN/inference_realesrgan.py",
    "-n",
    "RealESRGAN_x4plus",
    "-i",
    "./inputs",
    "--outscale",
    "4",
    "--model_path",
    "./Real-ESRGAN/experiments/finetune_RealESRGANx4plus_400k/models/net_g_latest.pth",
    "--output",
    "./result/Real-ESRGAN5000"
]

# 実行
result = subprocess.run(cmd, capture_output=True, text=True)

# 実行結果の確認
if result.returncode == 0:
  print("RealESRGAN-5000の推論が成功しました！")
  print(result.stdout)
else:
  print("エラーが発生しました:")
  print(result.stderr)

cmd = [
    "python",
    "./Real-ESRGAN/inference_realesrgan.py",
    "-n",
    "RealESRGAN_x4plus",
    "-i",
    "./inputs",
    "--outscale",
    "4",
    "--model_path",
    "./Real-ESRGAN/experiments/finetune_RealESRGANx4plus_400k3/models/net_g_latest.pth",
    "--output",
    "./result/Real-ESRGAN3000"
]

# 実行
result = subprocess.run(cmd, capture_output=True, text=True)

# 実行結果の確認
if result.returncode == 0:
  print("RealESRGAN-3000推論が成功しました！")
  print(result.stdout)
else:
  print("エラーが発生しました:")
  print(result.stderr)

cmd = [
    "python",
    "./Real-ESRGAN/inference_realesrgan.py",
    "-n",
    "RealESRNet_x4plus",
    "-i",
    "./inputs",
    "--outscale",
    "4",
    "--model_path",
    "./Real-ESRGAN/experiments/finetune_RealESRNetx4plus_400k/models/net_g_latest.pth",
    "--output",
    "./result/Real-ESRNet5000"
]

# 実行
result = subprocess.run(cmd, capture_output=True, text=True)

# 実行結果の確認
if result.returncode == 0:
  print("RealESRNetの推論が成功しました！")
  print(result.stdout)
else:
  print("エラーが発生しました:")
  print(result.stderr)

import subprocess


cmd = [
    "python",
    "./edsr/infer_edsr.py",
    "--weight_path",
    "./edsr/edsr_scale4_finetuned.onnx",
    "--input",
    "./inputs",
    "--savepath",
    "./result/edsr",
]

# 実行
result = subprocess.run(cmd, capture_output=True, text=True)

# 実行結果の確認
if result.returncode == 0:
  print("EDSRの推論が成功しました！")
  print(result.stdout)
else:
  print("エラーが発生しました:")
  print(result.stderr)

"""##　画像をくっつけるのを試してみる"""



batchsize = 4
threshold = 20.0
paths_input     = sorted(glob.glob('./inputs/*.tif'))
paths_gan5000   = sorted(glob.glob('./result/Real-ESRGAN5000/*.tif'))
paths_gan3000   = sorted(glob.glob('./result/Real-ESRGAN3000/*.tif'))
paths_net       = sorted(glob.glob('./result/Real-ESRNet5000/*.tif'))
paths_edsr      = sorted(glob.glob('./result/edsr/*.tif'))

os.makedirs('./result/mapping', exist_ok=True)


for p_in, p_5000, p_3000, p_net, p_edsr in zip(paths_input, paths_gan5000, paths_gan3000, paths_net, paths_edsr):

    img_in   = cv2.imread(p_in, cv2.IMREAD_GRAYSCALE)
    img_5000 = cv2.imread(p_5000, cv2.IMREAD_GRAYSCALE)
    img_3000 = cv2.imread(p_3000, cv2.IMREAD_GRAYSCALE)
    img_net  = cv2.imread(p_net, cv2.IMREAD_GRAYSCALE)
    img_edsr = cv2.imread(p_edsr, cv2.IMREAD_GRAYSCALE)

    if img_in is None:
        print(f"読み込み失敗: {p_in}")
        continue

    h, w = img_5000.shape[:2]
    img_in_resized = cv2.resize(img_in, (w, h), interpolation=cv2.INTER_CUBIC)

    std_map = np.zeros((h, w), dtype=np.float32)
    img_resized_pixel = np.array(img_in_resized)
    img_5000_pixel = np.array(img_5000)
    img_3000_pixel = np.array(img_3000)#dsr_batch_mean =
    img_net_pixel = np.array(img_net)
    img_edsr_pixel = np.array(img_edsr)
    for i in range(h//batchsize):
        for j in range(w//batchsize):
          img_in_batch = img_resized_pixel[i*batchsize:(i+1)*batchsize, j*batchsize:(j+1)*batchsize]
          img_5000_batch = img_5000_pixel[i*batchsize:(i+1)*batchsize, j*batchsize:(j+1)*batchsize]
          img_3000_batch = img_3000_pixel[i*batchsize:(i+1)*batchsize, j*batchsize:(j+1)*batchsize]
          img_net_batch = img_net_pixel[i*batchsize:(i+1)*batchsize, j*batchsize:(j+1)*batchsize]
          img_edsr_batch = img_edsr_pixel[i*batchsize:(i+1)*batchsize, j*batchsize:(j+1)*batchsize]
          img_in_batch_mean = np.max(img_in_batch)
          img_5000_batch_mean =np.max(img_5000_batch)
          img_3000_batch_mean=np.max(img_3000_batch)
          img_net_batch_mean = np.max(img_net_batch)
          img_edsr_batch_mean = np.max(img_edsr_batch)
          imgs = np.stack([img_in_batch_mean,img_5000_batch_mean,img_3000_batch_mean,img_net_batch_mean,img_edsr_batch_mean])
        # imgs = np.stack([img_in_batch, img_5000_batch, img_3000_batch, img_net_batch, img_edsr_batch], axis=0).astype(np.float32)
          std_map[i*batchsize:(i+1)*batchsize, j*batchsize:(j+1)*batchsize] = np.std(imgs, axis=0)
    mask = std_map > threshold

    color_result = cv2.cvtColor(img_in_resized, cv2.COLOR_GRAY2BGR)


    color_result[mask] = [0, 0, 255]

    # 7. 保存
    filename = os.path.basename(p_in)
    save_path = os.path.join('./result/mapping', f"map_{filename}")
    cv2.imwrite(save_path, color_result)

    print(f"処理完了: {save_path} (不確実領域の割合: {np.mean(mask)*100:.2f}%)")

#------------------------------------------------------------------------------------------------------------------------
#わかったこととしては、これはハルシネーションのようのものを検出することもできるけど、精度がめっちゃいいかと言われるとあまり良くない気がする。


